userclouds/terraform-provider-userclouds

.gitignore, docs/resources/access_policy.md, docs/resources/access_policy_template.md, docs/resources/userstore_accessor.md, docs/resources/userstore_mutator.md, genprovider/internal/apitypes/array.go, genprovider/internal/resources/resource.go, genprovider/internal/schemas/schemas.go, internal/provider/planmodifiers/increment_on_update.go, internal/provider/tokenizer/access_policy_resource_generated.go, internal/provider/tokenizer/access_policy_template_resource_generated.go, internal/provider/tokenizer/schemas_generated.go, internal/provider/userstore/schemas_generated.go, internal/provider/userstore/userstore_accessor_resource_generated.go, internal/provider/userstore/userstore_mutator_resource_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@78bd4feb51a84e2d224eb6fe32299aab9dabbc5a
=> Sync monorepo state at "Use gh instead of hub for repo syncs"

docs/resources/userstore_accessor.md, genprovider/internal/apitypes/string_enum.go, internal/provider/userstore/schemas_generated.go
Syncing from userclouds/userclouds@20e06326b9163a07f0acce0d328b986c2fd63b14
=> Sync monorepo state at "TF provider: fix generating accessor docs"

go.mod, go.sum
Syncing from userclouds/userclouds@6825017042094d0c3b7b477265b354b2572b3ce1
=> Sync monorepo state at "Bump github.com/mgechev/revive from 1.2.3 to 1.3.4"

openapi/userstore.yaml
Syncing from userclouds/userclouds@daea5b82e0df913fe35ba35c5170d6754a22dd63
=> Sync monorepo state at "user update uniqueness error fixes"

.gitignore
Syncing from userclouds/userclouds@e557d1b3925409240495e5268d756ff87009875b
=> Sync monorepo state at "Integrate python tooling (linters,formatters) into makefile (lint & lintfix targets)"

docs/resources/transformer.md, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@9ca186e199c1e1e8482e513c66f810f651870496
=> Sync monorepo state at "add output type for transformers"

docs/resources/transformer.md, go.mod, go.sum, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@9ee2ee76e0bb45f5c3081ab638784a3ec119efb8
=> Sync monorepo state at "Bump github.com/swaggest/openapi-go from 0.2.40 to 0.2.41"

openapi/tokenizer.yaml, openapi/userstore.yaml
Syncing from userclouds/userclouds@63226ddd501c474ac9e90e7a0e1fe4b32b114ac0
=> Sync monorepo state at "support case-insensitive matching of userstore objects and improve error handling"

go.mod, go.sum
Syncing from userclouds/userclouds@3a9970510545afaaee648b3ae2d2f634929bf68b
=> Sync monorepo state at "Bump google.golang.org/grpc from 1.56.1 to 1.56.3 in /public-repos/terraform-provider-userclouds"

go.mod, go.sum
Syncing from userclouds/userclouds@30f34984eab8824c6a75816485af63aa139879f2
=> Sync monorepo state at "Bump github.com/gofrs/uuid from 4.2.0+incompatible to 4.4.0+incompatible"

openapi/userstore.yaml
Syncing from userclouds/userclouds@df24eb4e81151ad415df9c688e71557bdf3ab98f
=> Sync monorepo state at "Use ucdb.IsUniqueViolation() to test for conflict"

openapi/userstore.yaml
Syncing from userclouds/userclouds@7d666e0f2c7b320a4514b0aa96870adbce0fcd7f
=> Sync monorepo state at "Adding /userstore/api/users handlers for creating user with mutator a…"

docs/resources/transformer.md, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@edda93adf32975d659f7064e2d83f1028a6a01a8
=> Sync monorepo state at "Fix marking transformer fields as optional"

Makefile, genprovider/config.json, genprovider/internal/apitypes/array.go, genprovider/internal/apitypes/bool.go, genprovider/internal/apitypes/float.go, genprovider/internal/apitypes/int.go, genprovider/internal/apitypes/map.go, genprovider/internal/apitypes/object.go, genprovider/internal/apitypes/string.go, genprovider/internal/apitypes/string_enum.go, genprovider/internal/apitypes/test_helper.go, genprovider/internal/apitypes/types.go, genprovider/internal/apitypes/types_test.go, genprovider/internal/apitypes/userstore_resource_id.go, genprovider/internal/apitypes/uuid.go, genprovider/internal/config/generation_config.go, genprovider/internal/schemas/schemas.go, internal/provider/tokenizer/schemas_generated.go, internal/provider/userstore/schemas_generated.go
Syncing from userclouds/userclouds@f22aeaa7b4dd1e3792e448899d59e79d7278c097
=> Sync monorepo state at "[terraform provider] Make column type/is_array immutable"

genprovider/internal/apitypes/test_helper.go
Syncing from userclouds/userclouds@e9db24ce00729eb8279c73768d851b6cf0ae3534
=> Sync monorepo state at "Fix TF provider test"

openapi/userstore.yaml
Syncing from userclouds/userclouds@f61d28b348edb7217bdd031237841ed019095850
=> Sync monorepo state at "accessor and mutator status code improvements"

docs/resources/userstore_mutator.md, internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@0490c9467fc1efb3035e3f6ace0e0525304bb7da
=> Sync monorepo state at "properly validate and execute normalizers and transformers in mutators and accessors"

internal/provider/provider.go
Syncing from userclouds/userclouds@8675ba8b23133086264633d4943aa58817d44cb7
=> Sync monorepo state at "Set User-Agent header for the terraform-provider-userclouds"

go.mod, go.sum, internal/provider/provider.go
Syncing from userclouds/userclouds@c3bd7a49bd42187f23109dbe8ecf55c5646e9f49
=> Sync monorepo state at "Cleanup some headers API usage, cleanup TODO"

openapi/userstore.yaml
Syncing from userclouds/userclouds@894e6883f0bbedcc652a24ead9ef3f9c45102875
=> Sync monorepo state at "Adding "region" option for CreateUser and CreateUserWithMutator APIs …"

.github/actions/go-setup/action.yml
Syncing from userclouds/userclouds@19ce81841a1da6f76fedb87d4dcfcb078a54fe78
=> Sync monorepo state at "Upgrade to actions/setup-go v5"

docs/resources/access_policy.md, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@1472a46dfb23e5c7326e42de4addc79590b83f65
=> Sync monorepo state at "Change compositeunion and compositeintersection to be composite_or and composite_and, fix reversal of these on frontend"

docs/resources/transformer.md, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@aacb37a0a11e4f6cc2f081696c11cf3071b4166a
=> Sync monorepo state at "Fix typos"

genprovider/internal/resources/resource.go, internal/provider/tokenizer/access_policy_resource_generated.go
Syncing from userclouds/userclouds@9d7916997cb9480f7c778381286b2d6d54bf1513
=> Sync monorepo state at "Prepare ucconfig for new release"

docs/resources/userstore_accessor.md, internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@a57f08165e074395d7406d3e7f29c7639a454dfc
=> Sync monorepo state at "Add IsAuditLogged flag to accessors"

openapi/userstore.yaml
Syncing from userclouds/userclouds@8332119cdb2a503ebbc39f25e88741eba3b41484
=> Sync monorepo state at "retain values properly when deleting user"

docs/resources/access_policy.md, docs/resources/transformer.md, docs/resources/userstore_column.md, genprovider/internal/resources/resource.go, internal/provider/tokenizer/access_policy_resource_generated.go, internal/provider/tokenizer/schemas_generated.go, internal/provider/userstore/schemas_generated.go, openapi/tokenizer.yaml, openapi/userstore.yaml
Syncing from userclouds/userclouds@f0c4bb0c82feb30b50b62d64e64debddb23450ae
=> Sync monorepo state at "Remove backcompat support for deprecated types "compositeunion" and "…"

.gitignore
Syncing from userclouds/userclouds@68af08ad9a65c5d7aaba9cd77f61676929cf5fee
=> Sync monorepo state at "Build & Use PEX file for datahub"

go.mod, go.sum
Syncing from userclouds/userclouds@da94922ede840f95a51ced7a146dfca5beb117f5
=> Sync monorepo state at "Upgrade to go 1.22"

go.mod, go.sum
Syncing from userclouds/userclouds@7b4a4773c40aa578e4e3bef265ba6befe5aaf6f8
=> Sync monorepo state at "follow up fixes for go 1.22.2 upgrade"

docs/resources/userstore_column.md, internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@852bd09a1e0559dd5b365f2c144efcdd0008bd55
=> Sync monorepo state at "sql shim - support multiple tables, support SSL/TLS"

genprovider/internal/stringutils/strcase.go, internal/provider/tokenizer/schemas_generated.go, internal/provider/userstore/schemas_generated.go
Syncing from userclouds/userclouds@ac29015bb854abadf7a33d14344980189f2bf88e
=> Sync monorepo state at "Fix new lint issues detected by the new version of Revive"

go.mod, go.sum
Syncing from userclouds/userclouds@367cab0d0a8444d3a80dd367ecb00bf55a0ce81a
=> Sync monorepo state at "Bump github.com/mgechev/revive from 1.3.4 to 1.3.7"

.gitignore
Syncing from userclouds/userclouds@7376ee57ee928afc166cf1d59c863e24e477a91f
=> Sync monorepo state at "Minor fixes"

.gitignore
Syncing from userclouds/userclouds@6607e8439d59522577026b046c0dabee318f2b04
=> Sync monorepo state at "Revert "Minor fixes (#4757)""

docs/resources/userstore_column.md, internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@bde13ba6a23eec005d3a3b65ed579e1ccf35bf47
=> Sync monorepo state at "Default transformers and token access policies for columns"

openapi/userstore.yaml
Syncing from userclouds/userclouds@b346ec1ceec469756d73a8cafc96609615e9e334
=> Sync monorepo state at "add multi-key pagination support for accessors"

go.mod, go.sum
Syncing from userclouds/userclouds@28fc8a39ab078ae8b3d9abb4b137d061e3a23e77
=> Sync monorepo state at "Bump mvdan.cc/sh/v3 from 3.7.0 to 3.8.0"

openapi/tokenizer.yaml, openapi/userstore.yaml
Syncing from userclouds/userclouds@11b980faba6eb53dad59c54e0d9ac11204ce5b01
=> Sync monorepo state at "update python and golang SDKs to reflect current supported pagination options"

go.mod
Syncing from userclouds/userclouds@12c945fe71ac2d67a4a0aa6d9f657f7a7039acaf
=> Sync monorepo state at "Add client side prometheus metrics to AWS SDK calls"

docs/resources/transformer.md, internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@b357a832a966e1f636bf405de3ba8ac45ff03148
=> Sync monorepo state at "Adding versions to transformers - phase 1"

docs/resources/transformer.md, docs/resources/userstore_column.md, internal/provider/tokenizer/schemas_generated.go, internal/provider/userstore/schemas_generated.go, openapi/tokenizer.yaml, openapi/userstore.yaml
Syncing from userclouds/userclouds@6345c984060e791d34f222ec54dc45c4e1002328
=> Sync monorepo state at "further DataType  cleanup"

.github/workflows/release.yaml
Syncing from userclouds/userclouds@27c042d79af4ded07d3102c69f6d9132b7fa8f59
=> Sync monorepo state at "Upgrade to latest goreleaser & goreleaser GHA"

.goreleaser.yml
Syncing from userclouds/userclouds@915ff937814610d37a2b39c1597e682438568173
=> Sync monorepo state at "Fix go releaser config files (upgrade to latest schema)"

go.mod, go.sum
Syncing from userclouds/userclouds@0a8407724ad59390ae87c845601803ef990898d4
=> Sync monorepo state at "Bump the open-telemetry-go group across 1 directory with 5 updates"

internal/provider/tokenizer/schemas_generated.go, openapi/tokenizer.yaml
Syncing from userclouds/userclouds@7ef9b3d575ef28893fbad784c57c0d94d776851c
=> Sync monorepo state at "Giving customers the ability to store secrets to be used in access policy templates and transformers"

.gitignore
Syncing from userclouds/userclouds@e36b587dcf97e48299d33a6f2034d9c567f053fc
=> Sync monorepo state at "allow ui-component-lib storybook to build successfully by swapping de…"

go.mod
Syncing from userclouds/userclouds@c09f10a45b659388693e84168adb4befe50a06b1
=> Sync monorepo state at "Upgrading to Go 1.23.1"

.gitignore
Syncing from userclouds/userclouds@2c16156114c61380673d3353bc6ae98ec5907233
=> Sync monorepo state at "Test that helm rendered manifests are valid k8s objects"

go.mod, go.sum
Syncing from userclouds/userclouds@ceb511b6d922db424561d05f83c76cf9d70808d0
=> Sync monorepo state at "Bump github.com/mgechev/revive from 1.4.0 to 1.5.0"

internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@da91ee74a3801994204c2ac90288acdb20ec859f
=> Sync monorepo state at "iterate over value ids when backfilling search"

internal/provider/userstore/schemas_generated.go, openapi/userstore.yaml
Syncing from userclouds/userclouds@e667ee4fe61f46b324e16c2184da18b15bc723e6
=> Sync monorepo state at "remove changefeed specific search management code"

go.mod, go.sum
Syncing from userclouds/userclouds@f117274d9b73eb3c0dd4eceaba1b1c76a5f09389
=> Sync monorepo state at "Bump helm.sh/helm/v3 from 3.16.4 to 3.17.0"

openapi/userstore.yaml
Syncing from userclouds/userclouds@a06a074e934cd2cb9edb4b01f59d566ccf4e7602
=> Sync monorepo state at "Add option to access primary db only for calls to retrieving user inf…"

.gitignore, openapi/userstore.yaml
Syncing from userclouds/userclouds@515ca073c72dd0761b3da5169f9036c41e0f574e
=> Sync monorepo state at "Ignore .yarn folders"

go.mod, go.sum
Syncing from userclouds/userclouds@99a4935fee426bbbed9a5a64df7bba5b298f4c4c
=> Sync monorepo state at "Bump mvdan.cc/sh/v3 from 3.10.0 to 3.11.0"

.gitignore
Syncing from userclouds/userclouds@fbd7617c8bd2cd8c0887c90343e9946f9dfa95d1
=> Sync monorepo state at "Don't commit anything from the bin/ folder + kill EB files in gitignore"
